// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDalTsxtzQGSqmcI7eBMih8k6ABBJ43ixc',
    appId: '1:138614339331:web:21e240edafd2c0f06e5b36',
    messagingSenderId: '138614339331',
    projectId: 'paws-fac7e',
    authDomain: 'paws-fac7e.firebaseapp.com',
    storageBucket: 'paws-fac7e.firebasestorage.app',
    measurementId: 'G-GDR0FB6MFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoXX7Sqq0U1EQDzGDgPW6ZAA6ZZNIb_SU',
    appId: '1:138614339331:android:cef300615c8932186e5b36',
    messagingSenderId: '138614339331',
    projectId: 'paws-fac7e',
    storageBucket: 'paws-fac7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzUwNujeK60nKAg-QOFbnHPjB3R6Kn-oo',
    appId: '1:138614339331:ios:a30c56898809c7fb6e5b36',
    messagingSenderId: '138614339331',
    projectId: 'paws-fac7e',
    storageBucket: 'paws-fac7e.firebasestorage.app',
    iosBundleId: 'com.example.pawtrustFresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzUwNujeK60nKAg-QOFbnHPjB3R6Kn-oo',
    appId: '1:138614339331:ios:a30c56898809c7fb6e5b36',
    messagingSenderId: '138614339331',
    projectId: 'paws-fac7e',
    storageBucket: 'paws-fac7e.firebasestorage.app',
    iosBundleId: 'com.example.pawtrustFresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDalTsxtzQGSqmcI7eBMih8k6ABBJ43ixc',
    appId: '1:138614339331:web:bbd5cc9c87f79ab16e5b36',
    messagingSenderId: '138614339331',
    projectId: 'paws-fac7e',
    authDomain: 'paws-fac7e.firebaseapp.com',
    storageBucket: 'paws-fac7e.firebasestorage.app',
    measurementId: 'G-2TYS45MH0Z',
  );
}
