// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGspQXSAf7oOH-qFglHOAG_gxXr3KiL8',
    appId: '1:347981346637:web:28a1a152c2c81947dba904',
    messagingSenderId: '347981346637',
    projectId: 'esg-supply-chain',
    authDomain: 'esg-supply-chain.firebaseapp.com',
    storageBucket: 'esg-supply-chain.firebasestorage.app',
    measurementId: 'G-KR7EBMD6Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzqLZ7UjsbtVTwf7_Qi8t3TAe7k-gNGAA',
    appId: '1:347981346637:android:fdc860ee9d5bbeabdba904',
    messagingSenderId: '347981346637',
    projectId: 'esg-supply-chain',
    storageBucket: 'esg-supply-chain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxin15KLSonBKq_YysP8vOONyAeOkM_ko',
    appId: '1:347981346637:ios:b2b17ecd5cc65afbdba904',
    messagingSenderId: '347981346637',
    projectId: 'esg-supply-chain',
    storageBucket: 'esg-supply-chain.firebasestorage.app',
    iosBundleId: 'com.example.pawtrustFresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxin15KLSonBKq_YysP8vOONyAeOkM_ko',
    appId: '1:347981346637:ios:b2b17ecd5cc65afbdba904',
    messagingSenderId: '347981346637',
    projectId: 'esg-supply-chain',
    storageBucket: 'esg-supply-chain.firebasestorage.app',
    iosBundleId: 'com.example.pawtrustFresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChGspQXSAf7oOH-qFglHOAG_gxXr3KiL8',
    appId: '1:347981346637:web:e3edd91cdb4af9c1dba904',
    messagingSenderId: '347981346637',
    projectId: 'esg-supply-chain',
    authDomain: 'esg-supply-chain.firebaseapp.com',
    storageBucket: 'esg-supply-chain.firebasestorage.app',
    measurementId: 'G-S92R05V6LN',
  );

}